# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'never'

# Bindings for normal mode
config.bind(';V', 'hint --rapid links spawn umpv {hint-url}')
config.bind(';v', 'hint links spawn umpv {hint-url}')
config.bind('<Alt+p>', 'tab-pin')
config.bind('<Space><Space>', 'set-cmd-text -s :buffer')
config.bind('<Space>d', 'close')
config.bind('<Space>p', 'spawn umpv {url}')
config.bind('D', None)
config.bind('X', 'undo')
config.bind('d', 'scroll-page 0 0.5')
config.bind('po', 'open --private')
config.bind('u', 'scroll-page 0 -0.5')
config.bind('x', 'tab-close')
config.bind('xO', None)
config.bind('xo', None)
config.bind('zl', 'spawn --userscript qute-pass')
config.bind('zol', 'spawn --userscript qute-pass --otp-only')
config.bind('zpl', 'spawn --userscript qute-pass --password-only')
config.bind('zul', 'spawn --userscript qute-pass --username-only')
