# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# Bindings for normal mode
config.bind(';V', 'hint --rapid links spawn umpv {hint-url}')
config.bind(';v', 'hint links spawn umpv {hint-url}')
config.bind('<Space><Space>', 'set-cmd-text -s :buffer')
config.bind('<Space>p', 'spawn umpv {url}')
config.bind('zl', 'spawn --userscript qute-pass')
config.bind('zol', 'spawn --userscript qute-pass --otp-only')
config.bind('zpl', 'spawn --userscript qute-pass --password-only')
config.bind('zul', 'spawn --userscript qute-pass --username-only')
