---
- hosts: local
  tasks:
    - group_by:
        key: "{{ ansible_os_family }}_virt_{{ ansible_virtualization_role|default('none', true) }}"

- hosts: Debian_virt_host
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - gui_development

- hosts: Debian_virt_guest
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - development

- hosts: Darwin_virt_none
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  roles:
    - mac
