---
- hosts: local
  tasks:
    - group_by:
        key: "{{ ansible_os_family }}-virt_{{ ansible_virtualization_role|default('none', true) }}"

- hosts: Debian-virt_host
  gather_facts: false
  roles:
    - physical

- hosts: Debian-virt_guest
  gather_facts: false
  roles:
    - common

- hosts: Darwin-virt_none
  gather_facts: false
  roles:
    - mac
