---

# https://github.com/flatpak/flatpak/issues/2031
- name: Install fcitx, fcitx-modules of sid
  apt:
    name:
      - fcitx
      - fcitx-modules
      # - fcitx5
      # - fcitx5-module-dbus
      # - fcitx5-pinyin
      # - kde-config-fcitx5
    default_release: sid
    state: latest
  become: yes

- name: Install fcitx, fcitx-config-gtk, fcitx-frontend-gtk3, fcitx-frontend-qt5, fcitx-ui-classic, fcitx-googlepinyin, fcitx-hangul, fcitx-mozc
  apt:
    name:
      # - fcitx
      - fcitx-config-gtk
      - fcitx-frontend-gtk3
      - fcitx-frontend-qt5
      - fcitx-ui-classic
      - fcitx-googlepinyin
      - fcitx-hangul
      - fcitx-mozc
    state: latest
  become: yes

- name: Ensure $HOME/.config/fcitx folder exist
  file:
    path: "{{ ansible_user_dir }}/.config/fcitx"
    state: directory

- name: Config fcitx
  copy:
    src: fcitx_config
    dest: "{{ ansible_user_dir }}/.config/fcitx/config"
