---
- include_vars: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_product_name | replace(' ', '_') | lower }}.yml"
      #skip: true

- import_tasks: flatpak.yml
  tags: flatpak
- import_tasks: sway.yml
  tags: sway
- import_tasks: browsers.yml
  tags: browsers
- import_tasks: cups.yml
  tags: cups
- import_tasks: driver.yml
  tags: driver
- import_tasks: fcitx.yml
  tags: fcitx
- import_tasks: fonts.yml
  tags: fonts
- import_tasks: multimedia.yml
  tags: multimedia
- import_tasks: network.yml
  tags: network

- name: Install skype from flathub for current user
  flatpak:
    name: com.skype.Client
    state: present
    method: user
  tags: skype

- name: Install slack from flathub for current user
  flatpak:
    name: com.slack.Slack
    state: present
    method: user
  tags: slack

- name: Install appimagelauncher, powertop
  apt:
    name:
      - appimagelauncher
      - powertop
    state: latest
  become: yes
