---
- include_vars: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_product_name | replace(' ', '_') | lower }}.yml"
      #skip: true

- import_tasks: sway.yml
- import_tasks: alacritty.yml
- import_tasks: browsers.yml
- import_tasks: cups.yml
- import_tasks: driver.yml
- import_tasks: fcitx.yml
- import_tasks: fonts.yml
- import_tasks: multimedia.yml
- import_tasks: network.yml
- import_tasks: skype.yml
- import_tasks: syncthing.yml

- name: Install appimagelauncher, powertop
  apt:
    name:
      - appimagelauncher
      - powertop
    state: latest
  become: yes
