---

- name: Install modemmanager, network-manager
  apt:
    name:
      - modemmanager
      - network-manager
    state: latest
  become: yes

- name: Remove ifupdown
  apt:
    name:
      - ifupdown
    state: absent
    purge: yes
  become: yes
