#!/bin/sh

# fcitx
export CLUTTER_IM_MODULE=xim
export QT4_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
# export QT4_IM_MODULE=fcitx5
# export QT_IM_MODULE=fcitx5
# export XMODIFIERS=@im=fcitx5
# export GTK_IM_MODULE=fcitx5

# firefox
export MOZ_ENABLE_WAYLAND=1

# vaapi
export LIBVA_DRIVER_NAME=iHD

# alacritty
export WINIT_UNIX_BACKEND=x11

# qt5
export QT_QPA_PLATFORMTHEME=qt5ct

exec sway
