---

- name: Install vagrant, virtualbox
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: true
  with_items:
    - vagrant
    - virtualbox

- name: Check install of vagrant-vbguest plugin
  shell: "vagrant plugin list | grep vbguest | wc -l"
  register: plugin_count
  changed_when: False

- name: Install vagrant-vbguest plugin
  shell: "vagrant plugin install vagrant-vbguest"
  when: plugin_count.stdout|int == 0

- name: Start up vagrant
  shell: "vagrant up"
