---

- name: Install buil-essential, cmake, fuse, socat
  apt:
    name:
      - build-essential
      - cmake
      #- cifs-utils
      #- dh-make
      #- git-buildpackage
      #- cowbuilder
      #- dnsutils
      - fuse                    # for appimages
      - socat
      #- universal-ctags
      #- zlib1g-dev
    state: latest
  become: yes

- name: Install golang, nnn of sid
  apt:
    name:
      - golang
      - nnn
    state: latest
    default_release: sid
  become: yes

- name: Install python packages of ansible, powerline-status
  pip:
    name:
      - ansible
      #- aws-shell
      #- httpie
      #- mycli==1.18.0
      #- pgcli
      - powerline-status
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo	ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: yes

- name: Set fs.inotify.max_user_watches to 524288 in /etc/sysctl.conf
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

# - name: config pbuilder
#   copy:
#     src: pbuilder/pbuilderrc
#     dest: "{{ ansible_user_dir }}/.pbuilderrc"
#
# - name: pbuilder hooks
#   copy:
#     src: pbuilder/hooks
#     dest: /var/cache/pbuilder/
#     mode: 0755
#   become: yes
#
# - name: Create Packages if not exists
#   copy:
#     src: pbuilder/Packages
#     dest: /var/cache/pbuilder/result/
#     force: no
#   become: yes
