---

- name: Install git
  apt:
    name: git
    state: latest
  become: yes

- name: Config git
  copy:
    src: git/config
    dest: "{{ ansible_user_dir }}/.gitconfig"
    force: no

- name: Config gitignore
  copy:
    src: git/ignore
    dest: "{{ ansible_user_dir }}/.config/git/"
    force: no
