# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

# editor
export EDITOR=vi

# Alias
alias 'ls=ls --color=auto'

# uniq environment variables
typeset -U path cdpath fpath manpath

case ${OSTYPE} in
    darwin*)
        # Alias
        alias 'll=ls -hlF'
        # homebrew
        if [[ -x $(command -v brew) ]]; then
            #path=(/usr/local/opt/coreutils/libexec/gnubin /usr/local/bin $path)
            path=(/usr/local/opt/coreutils/libexec/gnubin $path)
            MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
        fi
        # nodebrew
        if [[ -x $(command -v nodebrew) ]]; then
            path=($HOME/.nodebrew/current/bin $path)
        fi
        # powerline
        if [[ -d "$HOME/Library/Python/2.7/lib/python/site-packages/powerline" ]]; then
            export POWERLINE_ROOT="$HOME/Library/Python/2.7/lib/python/site-packages/powerline"
            path=($HOME/Library/Python/2.7/bin $path)
        fi
        # docker environment variables
        if [[ -z "$DOCKER_MACHINE_NAME" ]]; then
            eval $(docker-machine env)
        fi
        # http://yano3.hatenablog.jp/entry/2012/11/25/234244
        LC_CTYPE='en_US.UTF-8'
        ;;
    linux*)
        # Alias
        alias 'll=ls -lF'
        # user local bin
        if [[ -d "$HOME/.local/bin" ]]; then
            path=($HOME/.local/bin $path)
        fi
        # Powerline Root
        if [[ -d "/usr/share/powerline" ]]; then
            export POWERLINE_ROOT="/usr/share/powerline"
        fi
        ;;
esac

# powerline
if [[ -n "$POWERLINE_ROOT" ]]; then
    source "$POWERLINE_ROOT/bindings/zsh/powerline.zsh"
fi

# google cloud
if [[ -d "$HOME/google-cloud-sdk" ]]; then
    GOOGLE_CLOUD="$HOME/google-cloud-sdk"
    source $GOOGLE_CLOUD/path.zsh.inc
    source $GOOGLE_CLOUD/completion.zsh.inc
fi

# android sdk
if [[ -d "$HOME/android-sdk-linux" ]]; then
    path=($HOME/android-sdk-linux/platform-tools $path)
fi

# current bin directory
path=(bin(N-/) $path)

# ssh wrapper that rename current tmux window to the hostname of the remote host.
ssh() {
    # Do nothing if we are not inside tmux or ssh is called without arguments
    if [[ $# == 0 || -z $TMUX ]]; then
        command ssh $@
        return
    fi

    local old_name="$(tmux display -p '#W')"
    command ssh -o "PermitLocalCommand yes" -o "LocalCommand tmux rename-window %n" $@
    tmux rename-window "$old_name"
}

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
