---

- name: config i3
  copy: src=i3/ dest={{ ansible_user_dir }}/.i3

- name: config i3status
  template: src=i3status.conf.j2 dest={{ ansible_user_dir }}/.i3status.conf

- name: config roxterm
  copy: src=roxterm/ dest={{ ansible_user_dir }}/.config/roxterm.sourceforge.net

- name: config spotify
  copy: src=spotify.desktop dest={{ ansible_user_dir }}/.local/share/applications/spotify.desktop

- name: config external monitor udev rules
  template: src=udev/rules.d/90-monitor-hotplug.rules.j2 dest=/etc/udev/rules.d/90-monitor-hotplug.rules
  become: yes

- name: be sure {{ ansible_user_dir }}/.local/bin folder exists
  file: path={{ ansible_user_dir }}/.local/bin state=directory

- name: config udev monitor_hotplug programs
  template: src=udev/bin/monitor_hotplug.sh.j2 dest={{ ansible_user_dir }}/.local/bin/monitor_hotplug.sh

- name: confir xsessionrc
  copy: src=xsessionrc dest={{ ansible_user_dir }}/.xsessionrc
