---

- name: config git
  copy: src=gitconfig dest={{ ansible_user_dir }}/.gitconfig

- name: config zsh
  copy: src=zshrc dest={{ ansible_user_dir }}/.zshrc

- name: change login shell
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh
  become: yes

- name: config i3
  copy: src=i3/ dest={{ ansible_user_dir }}/.i3

- name: config i3status
  template: src=i3status.conf.j2 dest={{ ansible_user_dir }}/.i3status.conf

- name: config roxterm
  copy: src=roxterm/ dest={{ ansible_user_dir }}/.config/roxterm.sourceforge.net

#- name: config vim
#  copy: src=vim/ dest={{ ansible_user_dir }}

#- name: install vim plugins
#  shell: vim -u {{ ansible_user_dir }}/.vim/plugin.vim +PluginInstall +qall

- name: confir xsessionrc
  copy: src=xsessionrc dest={{ ansible_user_dir }}/.xsessionrc
