---

- name: Install fish
  apt:
    name: fish
    state: latest
  become: yes

- name: Config fish
  copy:
    src: fish
    dest: "{{ ansible_user_dir }}/.config/"

- name: Set fish as login shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
  become: yes
